# Generated by Django 4.2.5 on 2023-09-20 08:42

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=users.models.get_image_filename),
        ),
    ]
