# Generated by Django 4.2.5 on 2023-09-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_bio_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
