# Generated by Django 4.2.5 on 2023-09-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Avatar',
        ),
    ]
