# Generated by Django 4.2.5 on 2023-11-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_firebasetoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirebaseToken',
            new_name='UserDevice',
        ),
    ]
