# Generated by Django 4.2.5 on 2023-11-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_firebasetoken_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='type',
            field=models.CharField(choices=[('web', 'Web'), ('android', 'Andorid'), ('ios', 'Ios')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='firebase_token',
            field=models.CharField(max_length=200),
        ),
    ]
