# Generated by Django 4.2.5 on 2023-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userdevice_type_alter_userdevice_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='type',
            field=models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'Ios')], max_length=10),
        ),
    ]
