# Generated by Django 4.2.5 on 2023-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='bought',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
