# Generated by Django 4.2.5 on 2023-09-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_total_price_remove_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bought',
        ),
    ]
