# Generated by Django 4.2.5 on 2023-09-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_item',
            new_name='items',
        ),
    ]
