# Generated by Django 4.2.5 on 2023-09-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_cart_item_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='carts',
        ),
    ]
