# Generated by Django 4.2.5 on 2023-09-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='body',
            field=models.TextField(default=1, verbose_name='Book description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.BooleanField(default=False, verbose_name='like'),
        ),
    ]
