# Generated by Django 4.2.5 on 2023-09-12 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_book_body_book_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='like',
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='book_likes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
