# Generated by Django 4.2.5 on 2023-09-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.BooleanField(default=False, verbose_name='like'),
        ),
    ]
