# Generated by Django 4.2.5 on 2023-09-26 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0016_remove_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='book',
            new_name='book_id',
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('book_id', 'user')},
        ),
    ]
