# Generated by Django 4.2.5 on 2023-09-26 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0017_rename_book_bookrating_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='user',
            new_name='use_id',
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('book_id', 'use_id')},
        ),
    ]
