# Generated by Django 4.2.5 on 2023-09-26 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0018_rename_user_bookrating_use_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='use_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('book_id', 'user')},
        ),
    ]
