# Generated by Django 4.2.5 on 2023-09-26 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0019_rename_use_id_bookrating_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='book_id',
            new_name='book',
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('book', 'user')},
        ),
    ]
