# Generated by Django 4.2.5 on 2023-09-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_remove_comment_owner_remove_comment_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
