# Generated by Django 4.2.5 on 2023-09-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
