# Generated by Django 4.2.5 on 2023-09-27 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0030_remove_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('book', 'user')},
        ),
    ]
