# Generated by Django 4.2.5 on 2023-09-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_alter_comment_options_rename_body_comment_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
    ]
