# Generated by Django 4.2.5 on 2023-09-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_rename_comment_comment_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
