# Generated by Django 4.2.5 on 2023-09-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
