# Generated by Django 4.2.5 on 2023-09-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='body',
        ),
    ]
