# Generated by Django 4.2.5 on 2023-09-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_bio_alter_customuser_username'),
        ('books', '0037_rename_comments_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.avatar'),
            preserve_default=False,
        ),
    ]
