# Generated by Django 4.2.5 on 2023-09-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0047_remove_book_store_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='store_amount',
            field=models.IntegerField(default=1),
        ),
    ]
