# Generated by Django 4.2.5 on 2023-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0049_remove_book_available_remove_book_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='store_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='BookStatus',
        ),
    ]
