# Generated by Django 4.2.5 on 2023-10-01 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0050_book_available_book_store_amount_delete_bookstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
