# Generated by Django 4.2.5 on 2023-10-02 08:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0051_alter_bookrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_rating', to='books.bookrating'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
