# Generated by Django 4.2.5 on 2023-10-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0052_book_rating_alter_bookrating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
