# Generated by Django 4.2.5 on 2023-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0053_remove_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='recommendation',
            field=models.BooleanField(default=True),
        ),
    ]
