# Generated by Django 4.2.5 on 2023-10-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0054_book_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='recommendation',
            field=models.BooleanField(default=False),
        ),
    ]
