# Generated by Django 4.2.5 on 2023-10-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0055_alter_book_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklike',
            old_name='book',
            new_name='book_id',
        ),
    ]
