# Generated by Django 4.2.5 on 2023-10-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0056_rename_book_booklike_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklike',
            old_name='book_id',
            new_name='book',
        ),
    ]
