# Generated by Django 4.2.5 on 2023-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0057_rename_book_id_booklike_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
