# Generated by Django 4.2.5 on 2023-10-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0060_rename_booklike_bookfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='store_amount',
        ),
    ]
