# Generated by Django 4.2.5 on 2023-11-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0061_remove_book_store_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
